"""update post table

Revision ID: 174a1d30bbbe
Revises: dfcddbcb65db
Create Date: 2019-04-13 22:07:55.271773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174a1d30bbbe'
down_revision = 'dfcddbcb65db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tags', sa.Column('post_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'post_count')
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###
