"""add some field in Post table

Revision ID: 9fe8c9125509
Revises: 174a1d30bbbe
Create Date: 2019-04-13 22:55:10.550520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe8c9125509'
down_revision = '174a1d30bbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_draft', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('image_url', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('is_draft', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_draft')
    op.drop_column('posts', 'image_url')
    op.drop_column('posts', 'body_draft')
    # ### end Alembic commands ###
